[project]
name = 'Tokenized-Telecommunications-Emergency-Communication-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.backup-coordination]
path = 'contracts/backup-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.emergency-service-verification]
path = 'contracts/emergency-service-verification.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
